---
deployment:
  tasks:
    - export DEPLOYPATH=/home/bezuide3/greatvibes.co.za/
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R mail $DEPLOYPATH
    - /bin/cp -R scss $DEPLOYPATH
    - /bin/cp -R vendor $DEPLOYPATH
    - /bin/cp *.* $DEPLOYPATH
    