# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Mon, 30 Aug 2021 07:07:52 +0000
*	@ALL	0
dnd5e:*	@dnd	1
general:*	@user	1
general:*	@dnd	1
home	@dnd	1
home	@user	1
