<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: lee
 * Date: Wed, 01 Sep 2021 08:37:39 +0200
 */

$conf['title'] = 'Lee\'s Grouping of Things';
$conf['start'] = 'home';
$conf['sidebar'] = 'general:sidebar';
$conf['license'] = 'cc-by-sa';
$conf['breadcrumbs'] = 0;
$conf['dformat'] = '%Y/%m/%d %a %H:%M';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['proxy']['user'] = 'Lee';
$conf['proxy']['pass'] = '<b>TkB0djBkYWYwbmUyMDIx';
$conf['tpl']['bootstrap3']['bootswatchTheme'] = 'darkly';
$conf['tpl']['bootstrap3']['socialShareProviders'] = 'facebook,linkedin,microsoft-teams,pinterest,whatsapp,reddit,twitter,telegram,yammer,google-plus';
$conf['tpl']['mindthedark']['theme'] = 'dark';
$conf['tpl']['mindthedark']['autoDark'] = '1';
$conf['tpl']['mindthedark']['userChoice'] = '1';
$conf['tpl']['mindthedark']['pluginNote'] = '1';
