# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Mon, 30 Aug 2021 07:07:52 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

lee:$2y$10$YWoJH5NxeniZZsHtHqTDyOvw6vqPi86BiLJEv09ZxQelVT/OLEF8i:Lee:scubapetey@gmail.com:admin,user
dnd:$2y$10$UtQN1d4UOLFQBzAQ812aJuN7FvUEDLAg4jwvkzsdjZtscowkjlHuW:dnd:dnd@dnd:dnd
user:$2y$10$E70WGTybZd2gYZHbZJLtxediWXzCyYExnVrkGIaGf8w8wf.iwNkiu:user:scubapetey@gmail.com:user
